In [ ]:
#Pandas Serice
# A serice is a  one diamensional lable array capable of holding any data type

In [5]:
import numpy as np

import  pandas as pd
print('kjcmjf')

kjcmjf

In [6]:
label=['a','b','c']
my_list=[10,20,30]

arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [12]:
pd.Series(my_list)

pd.Series(d)
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.2.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import numpy as np
import  pandas as pd
data = {
    "Name": ["Uvesh", "Rahul", "Aman", "Priya", "Neha"],
    "Age": [22, 24, 21, 23, 25],
    "City": ["Ghaziabad", "Delhi", "Noida", "Meerut", "Gurgaon"],
    "Salary": [25000, 30000, 22000, 28000, 35000]
}
df=pd.DataFrame(data)

In [15]:
df

    Name  Age       City  Salary
0  Uvesh   22  Ghaziabad   25000
1  Rahul   24      Delhi   30000
2   Aman   21      Noida   22000
3  Priya   23     Meerut   28000
4   Neha   25    Gurgaon   35000

In [23]:
data_list=[
    ['john',28,'new york',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]

df2=pd.DataFrame(data_list)
columns=['Name',"age",'City','salary']
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  age      City  salary
0   john   28  new york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df2

    Name  age      City  salary
0   john   28  new york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2[['Name','age']]

    Name  age
0   john   28
1   Anna   34
2  Peter   29
3  Linda   42

In [30]:
df2['designation']=['doctor','engineer','doctor','engineer']

In [33]:
df2

    Name  age      City  salary designation
0   john   28  new york   65000      doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000    engineer

In [36]:
df2.drop('designation',axis=1,inplace=True)

In [38]:
df2.drop(['age','City'],axis=1)

    Name  salary
0   john   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [40]:
df2.drop(['age','Name','salary'],axis=1)
df2

    Name  age      City  salary
0   john   28  new york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
data_list = [

    ['Rahul', 25, 'Mumbai', 55000],

    ['Sneha', 31, 'Bangalore', 72000],

    ['Arjun', 27, 'Hyderabad', 48000],

    ['Meena', 38, 'Chennai', 81000],

    ['Karan', 23, 'Pune', 42000]

]
a=pd.DataFrame(data_list)
columns=['Name','Age',"City",'Salary']

b=pd.DataFrame(data_list,columns=columns)
b

    Name  Age       City  Salary
0  Rahul   25     Mumbai   55000
1  Sneha   31  Bangalore   72000
2  Arjun   27  Hyderabad   48000
3  Meena   38    Chennai   81000
4  Karan   23       Pune   42000

In [49]:
df2
df2.drop([2,3],axis=0)

   Name  age      City  salary
0  john   28  new york   65000
1  Anna   34     Paris   70000

In [50]:
df2

    Name  age      City  salary
0   john   28  new york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [51]:
df2.loc[[0,1]]

   Name  age      City  salary
0  john   28  new york   65000
1  Anna   34     Paris   70000

In [52]:
df2

    Name  age      City  salary
0   john   28  new york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [56]:
df2.loc[[0,1]][['City','salary']]

       City  salary
0  new york   65000
1     Paris   70000

In [57]:
df2

    Name  age      City  salary
0   john   28  new york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [60]:
df2.loc[[1,2]][['City','age']]

     City  age
1   Paris   34
2  Berlin   29

In [66]:
df2[(df2['age']>30) & (df2['City']=='Paris')]

   Name  age   City  salary
1  Anna   34  Paris   70000

In [62]:
df2[df2['salary']>70000]

    Name  age    City  salary
3  Linda   42  London   85000

In [ ]:
# Mission

In [3]:
print('python')

python

In [ ]:
import numpy as np
import  pandas as pd
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 3, 4, 5, 6],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [10]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [11]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [12]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [13]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [14]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [15]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [16]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [17]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
4  5.0  6  NaN  5.0

In [18]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [19]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  0.0
2  0.0  4  3.0  0.0
3  4.0  5  0.0  0.0
4  5.0  6  0.0  5.0

In [22]:
values={'A':0,'B':100,'C':300,'D':400}

df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  3    2.0  400.0
2  0.0  4    3.0  400.0
3  4.0  5  300.0  400.0
4  5.0  6  300.0    5.0

In [23]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  3.0
2  3.0  4  3.0  3.0
3  4.0  5  2.0  3.0
4  5.0  6  2.0  5.0

In [24]:
df.mean()

A    3.0
B    3.8
C    2.0
D    3.0
dtype: float64

In [ ]:
# data filling

In [29]:
import numpy as np
import pandas as pd

data = {
    'A': [12, 18, np.nan, 25, 31],
    'B': [5, 6, 14, 22, 29],
    'C': [8, 11, 17, np.nan, np.nan],
    'D': [3, np.nan, np.nan, 19, 27],
    'E':[5,np.nan,np.nan,30,12]
}

df2=pd.DataFrame(data)

In [31]:
df2

      A   B     C     D     E
0  12.0   5   8.0   3.0   5.0
1  18.0   6  11.0   NaN   NaN
2   NaN  14  17.0   NaN   NaN
3  25.0  22   NaN  19.0  30.0
4  31.0  29   NaN  27.0  12.0

In [32]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [33]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [34]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [35]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [37]:
df.dropna(thresh=2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [38]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  0.0
2  0.0  4  3.0  0.0
3  4.0  5  0.0  0.0
4  5.0  6  0.0  5.0

In [39]:
values={'A':10,'B':34,'C':56,'D':89}

df.fillna(value=values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  3   2.0  89.0
2  10.0  4   3.0  89.0
3   4.0  5  56.0  89.0
4   5.0  6  56.0   5.0

In [40]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  NaN
2  NaN  4  3.0  NaN
3  4.0  5  NaN  NaN
4  5.0  6  NaN  5.0

In [41]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  3  2.0  3.0
2  3.0  4  3.0  3.0
3  4.0  5  2.0  3.0
4  5.0  6  2.0  5.0

In [ ]:
import numpy as np
import pandas as pd

In [42]:
import pandas as pd

# DataFrame 1: Employees information
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[60000,80000,65000,70000,90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [43]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [44]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [47]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [48]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [49]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [50]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [51]:
import pandas as pd

# DataFrame 1
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

# DataFrame 2
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [52]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [53]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [54]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [57]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
# **joinging 2 data frame

In [59]:
import pandas as pd

# First DataFrame
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [60]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [62]:
df2

   score
2     85
3     90
4     75

In [64]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [69]:
df2.join(df1,how='inner')

   score     name
2     85      Bob
3     90  Charlie

In [71]:
import pandas as pd

# Creating the data dictionary
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

# Creating the DataFrame
df = pd.DataFrame(data)

In [72]:
data

{'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
 'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
 'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
 'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
 'Date': DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
                '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08'],
               dtype='datetime64[ns]', freq='D')}

In [73]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [79]:
cat=df.groupby('Category')['Sales'].sum()
cat

# for i,v in cat:
#     print(i)
#     print(v)

Category
A    570
B    930
Name: Sales, dtype: int64

In [81]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [83]:
df.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [84]:
df['Sales'].mean()

np.float64(187.5)

In [85]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [88]:
df['Sales'].median()

np.float64(190.0)

In [89]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [92]:
df['Sales'].agg(['sum','min','mean','max','count','std','median'])

sum       1500.000000
min        100.000000
mean       187.500000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [ ]:
import numpy as np
import pandas as pd

In [93]:
import pandas as pd
import numpy as np

# Creating the data dictionary
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Adding Month and Quarter columns
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [94]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    346     39   John  January      Q1
1  2023-01-02       B   West    932     47   Mary  January      Q1
2  2023-01-03       C  North    439     75    Bob  January      Q1
3  2023-01-04       D  South    393     16  Alice  January      Q1
4  2023-01-05       A   East    520     71   John  January      Q1
5  2023-01-06       B   West    917     14   Mary  January      Q1
6  2023-01-07       C  North    940     71    Bob  January      Q1
7  2023-01-08       D  South    975     64  Alice  January      Q1
8  2023-01-09       A   East    739     35   John  January      Q1
9  2023-01-10       B   West    374     47   Mary  January      Q1
10 2023-01-11       C  North    594     15    Bob  January      Q1
11 2023-01-12       D  South    994     95  Alice  January      Q1
12 2023-01-13       A   East    854     49   John  January      Q1
13 2023-01-14       B   West    123     17   Mary  January      Q1
14 2023-01-15       C  North    146     72    Bob  January      Q1
15 2023-01-16       D  South    991     28  Alice  January      Q1
16 2023-01-17       A   East    616     95   John  January      Q1
17 2023-01-18       B   West    985     56   Mary  January      Q1
18 2023-01-19       C  North    524     82    Bob  January      Q1
19 2023-01-20       D  South    557     39  Alice  January      Q1

In [97]:
df.groupby(['Product','Region'])

In [99]:
pd.pivot_table(df,values='Sales',index='Region',columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     616.0    NaN    NaN    NaN
North      NaN    NaN  524.0    NaN
South      NaN    NaN    NaN  975.0
West       NaN  917.0    NaN    NaN

In [101]:
pivot2=pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')

In [102]:
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     615.0    NaN    NaN    NaN  57.8   NaN   NaN   NaN
North      NaN    NaN  528.6    NaN   NaN   NaN  63.0   NaN
South      NaN    NaN    NaN  782.0   NaN   NaN   NaN  48.4
West       NaN  666.2    NaN    NaN   NaN  36.2   NaN   NaN

In [103]:
import pandas as pd

# Creating the DataFrame with full data
df1 = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C': [100, 200, 300, 400, 500]
})

In [104]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [105]:
df1.shape

(5, 3)

In [106]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [107]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 248.0 bytes

In [108]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [109]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
df1['B']

In [4]:
import numpy as np
import pandas as pd


df=pd.read_csv(r"C:\Users\Dell\Downloads\anime.csv")

In [ ]:
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [6]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [8]:
df.loc[4]['Title']

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [12]:
def extract_episodes(txt):
    
    check = False
    data = ""

    for i in txt:
        if i == ")":
            check = False
            return data

        if check == True:
            data = data + i

        if i == "(":
            check = True

In [14]:
df['Episodes']=df['Title'].apply(extract_episodes)

In [20]:
df['Episodes']=df['Episodes'].str.replace('eps',"")

In [21]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04      51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04       1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04     148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04      13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03      13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03       2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02     110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99      13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99      13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98      12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94     201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94       1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93      22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93      24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91      25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91       1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89       1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88       7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88      14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87      74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84       1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84       1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83      12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83       1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82      24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82      23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81      12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81      26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80      13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80      16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79      11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79       1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79      11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78      10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78       1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77      26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77      12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76      75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75      26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75      26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74      24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73      10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72      12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71      12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71       4

In [24]:
df.loc[0]['Episodes']

'64 '

In [26]:
df['Episodes']=df['Episodes'].astype(int)

In [27]:
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

In [29]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [ ]:
def extraction_time(txt):